import IIdGenerator from '@/infra/id-generator/uuid'
import { faker } from '@faker-js/faker'
import * as uuid from 'uuid'

jest.mock('uuid')

describe('UUID IdGenerator', () => {
  let id: string
  let uuidSpy: any
  let sut: IIdGenerator

  beforeAll(() => {
    id = faker.datatype.uuid()
    uuidSpy = jest.spyOn(uuid, 'v4').mockReturnValue(id)
  })

  beforeEach(() => {
    sut = new IIdGenerator()
  })

  it('should return an id generated by uuid', async () => {
    const generatedId = sut.perform()

    expect(uuidSpy).toHaveBeenCalledTimes(1)
    expect(generatedId).toBe(id)
  })
})
